class EmojiMap {
  /// Returns the best matching emoji for the given text.
  /// Checks each word in the input against the keyword map.
  /// Falls back to '📌' if no match is found.
  static String getEmoji(String text) {
    final lower = text.toLowerCase();

    // First, try multi-word matches (more specific)
    for (final entry in _multiWordKeywords.entries) {
      if (lower.contains(entry.key)) return entry.value;
    }

    // Then, try single-word matches
    final words = lower.split(RegExp(r'[\s,.\-!?;:]+'));
    for (final word in words) {
      final emoji = _keywords[word];
      if (emoji != null) return emoji;
    }

    return '📌';
  }

  // ── Multi-word keywords (checked first for specificity) ──────────────
  static const Map<String, String> _multiWordKeywords = {
    'morning walk': '🌅',
    'phone repair': '📱',
    'water plants': '🌿',
    'water plant': '🌿',
    'ice cream': '🍦',
    'credit card': '💳',
    'debit card': '💳',
    'blood test': '🩸',
    'eye doctor': '👁️',
    'hair cut': '💇',
    'post office': '🏤',
    'grocery store': '🛒',
    'gas station': '⛽',
    'pet shop': '🐾',
    'dry cleaning': '👔',
    'car wash': '🚿',
    'oil change': '🔧',
    'take out': '🥡',
    'take away': '🥡',
    'pick up': '📦',
    'drop off': '📦',
    'sign up': '📝',
    'work out': '💪',
    'alarm clock': '⏰',
    'first aid': '🩹',
    'social media': '📱',
    'bus ticket': '🎫',
    'train ticket': '🎫',
    'movie ticket': '🎟️',
    'thank you': '🙏',
    'happy birthday': '🎂',
    'good morning': '🌅',
    'good night': '🌙',
    'tooth brush': '🪥',
    'hand wash': '🧴',
    'face wash': '🧴',
    'mobile recharge': '📱',
    'electricity bill': '💡',
    'water bill': '💧',
    'phone bill': '📞',
    'internet bill': '🌐',
    'gas bill': '🔥',
  };

  // ── Single-word keywords ─────────────────────────────────────────────
  static const Map<String, String> _keywords = {
    // Food & Groceries
    'egg': '🥚',
    'eggs': '🥚',
    'milk': '🥛',
    'bread': '🍞',
    'rice': '🍚',
    'chicken': '🍗',
    'meat': '🥩',
    'fish': '🐟',
    'vegetable': '🥬',
    'vegetables': '🥬',
    'fruit': '🍎',
    'fruits': '🍎',
    'apple': '🍎',
    'banana': '🍌',
    'orange': '🍊',
    'mango': '🥭',
    'sugar': '🍬',
    'salt': '🧂',
    'oil': '🫒',
    'butter': '🧈',
    'cheese': '🧀',
    'pizza': '🍕',
    'burger': '🍔',
    'noodles': '🍜',
    'cake': '🎂',
    'chocolate': '🍫',
    'snack': '🍿',
    'snacks': '🍿',
    'grocery': '🛒',
    'groceries': '🛒',
    'food': '🍕',

    // Meals
    'lunch': '🍽️',
    'dinner': '🍽️',
    'breakfast': '🥐',
    'brunch': '🥞',

    // Drinks
    'coffee': '☕',
    'tea': '🍵',
    'water': '💧',
    'juice': '🧃',
    'drink': '🥤',
    'beer': '🍺',
    'wine': '🍷',
    'smoothie': '🥤',
    'soda': '🥤',

    // Communication
    'call': '📞',
    'phone': '📞',
    'email': '📧',
    'mail': '📧',
    'message': '💬',
    'chat': '💬',
    'text': '💬',
    'letter': '✉️',
    'whatsapp': '💬',

    // Home
    'rent': '🏠',
    'house': '🏠',
    'home': '🏠',
    'apartment': '🏢',
    'furniture': '🪑',
    'sofa': '🛋️',
    'bed': '🛏️',
    'curtain': '🪟',
    'curtains': '🪟',
    'kitchen': '🍳',
    'bathroom': '🚿',
    'garden': '🌱',
    'plant': '🌱',
    'plants': '🌱',
    'flower': '🌸',
    'flowers': '🌸',

    // Cleaning
    'clean': '🧹',
    'cleaning': '🧹',
    'laundry': '👕',
    'wash': '🧽',
    'iron': '👔',
    'ironing': '👔',
    'mop': '🧹',
    'sweep': '🧹',
    'vacuum': '🧹',
    'dust': '🧹',
    'trash': '🗑️',
    'garbage': '🗑️',

    // Fitness & Health
    'gym': '💪',
    'workout': '💪',
    'exercise': '💪',
    'run': '🏃',
    'running': '🏃',
    'jog': '🏃',
    'jogging': '🏃',
    'walk': '🚶',
    'walking': '🚶',
    'swim': '🏊',
    'swimming': '🏊',
    'cycle': '🚲',
    'cycling': '🚲',
    'yoga': '🧘',
    'meditate': '🧘',
    'meditation': '🧘',
    'stretch': '🤸',
    'pushup': '💪',
    'pushups': '💪',
    'plank': '💪',
    'weight': '🏋️',
    'weights': '🏋️',
    'protein': '💪',
    'diet': '🥗',
    'salad': '🥗',
    'health': '❤️',
    'healthy': '❤️',
    'steps': '👟',

    // Medical
    'medicine': '💊',
    'pill': '💊',
    'pills': '💊',
    'tablet': '💊',
    'doctor': '🏥',
    'hospital': '🏥',
    'clinic': '🏥',
    'dentist': '🦷',
    'teeth': '🦷',
    'checkup': '🩺',
    'vaccine': '💉',
    'injection': '💉',
    'pharmacy': '💊',
    'prescription': '📋',
    'therapy': '🧠',

    // Sleep & Rest
    'sleep': '😴',
    'nap': '😴',
    'rest': '😴',
    'bedtime': '🌙',

    // Work & Office
    'office': '💼',
    'work': '💼',
    'meeting': '📋',
    'presentation': '📊',
    'project': '📂',
    'deadline': '⏰',
    'report': '📄',
    'interview': '🤝',
    'resume': '📄',
    'salary': '💰',
    'bonus': '💰',
    'client': '🤝',
    'boss': '👔',

    // Education & Learning
    'read': '📚',
    'reading': '📚',
    'book': '📖',
    'books': '📖',
    'study': '📝',
    'studying': '📝',
    'learn': '📝',
    'learning': '📝',
    'course': '🎓',
    'class': '🎓',
    'exam': '📝',
    'test': '📝',
    'homework': '📝',
    'assignment': '📝',
    'school': '🏫',
    'college': '🎓',
    'university': '🎓',
    'tutorial': '📝',
    'lecture': '🎓',
    'library': '📚',
    'notebook': '📓',
    'pen': '🖊️',

    // Finance
    'pay': '💳',
    'payment': '💳',
    'bill': '🧾',
    'bills': '🧾',
    'emi': '🏦',
    'loan': '🏦',
    'invest': '📈',
    'investment': '📈',
    'stock': '📈',
    'stocks': '📈',
    'mutual': '📈',
    'insurance': '🛡️',
    'tax': '🧾',
    'taxes': '🧾',
    'bank': '🏦',
    'atm': '🏧',
    'money': '💰',
    'cash': '💵',
    'savings': '🏦',
    'budget': '📊',
    'receipt': '🧾',
    'recharge': '📱',
    'subscription': '📋',

    // Transport
    'train': '🚂',
    'flight': '✈️',
    'airplane': '✈️',
    'airport': '✈️',
    'travel': '🧳',
    'trip': '🧳',
    'vacation': '🏖️',
    'holiday': '🏖️',
    'car': '🚗',
    'drive': '🚗',
    'driving': '🚗',
    'petrol': '⛽',
    'fuel': '⛽',
    'diesel': '⛽',
    'gas': '⛽',
    'bike': '🏍️',
    'bus': '🚌',
    'cab': '🚕',
    'taxi': '🚕',
    'uber': '🚕',
    'ola': '🚕',
    'auto': '🛺',
    'rickshaw': '🛺',
    'metro': '🚇',
    'parking': '🅿️',
    'toll': '🛣️',
    'ticket': '🎫',

    // Cooking
    'cook': '👨‍🍳',
    'cooking': '👨‍🍳',
    'recipe': '📖',
    'bake': '🧁',
    'baking': '🧁',
    'grill': '🥩',

    // Shopping
    'shop': '🛍️',
    'shopping': '🛍️',
    'buy': '🛒',
    'purchase': '🛒',
    'order': '📦',
    'delivery': '📦',
    'amazon': '📦',
    'flipkart': '📦',
    'online': '🌐',
    'return': '📦',
    'exchange': '🔄',
    'coupon': '🏷️',
    'discount': '🏷️',
    'sale': '🏷️',

    // Celebrations
    'birthday': '🎂',
    'party': '🎉',
    'celebrate': '🎉',
    'celebration': '🎉',
    'anniversary': '💍',
    'wedding': '💒',
    'gift': '🎁',
    'present': '🎁',
    'festival': '🎊',
    'diwali': '🪔',
    'christmas': '🎄',
    'holi': '🎨',
    'puja': '🙏',
    'eid': '🌙',

    // Entertainment
    'movie': '🎬',
    'film': '🎬',
    'cinema': '🎬',
    'netflix': '📺',
    'tv': '📺',
    'show': '📺',
    'series': '📺',
    'youtube': '▶️',
    'video': '🎥',
    'game': '🎮',
    'gaming': '🎮',
    'music': '🎵',
    'song': '🎵',
    'guitar': '🎸',
    'piano': '🎹',
    'dance': '💃',
    'concert': '🎤',
    'podcast': '🎙️',
    'cricket': '🏏',
    'football': '⚽',
    'badminton': '🏸',
    'tennis': '🎾',

    // Beauty & Grooming
    'haircut': '💇',
    'salon': '💇',
    'spa': '🧖',
    'facial': '🧖',
    'shave': '🪒',
    'makeup': '💄',
    'skincare': '🧴',

    // People
    'dad': '👨',
    'father': '👨',
    'mom': '👩',
    'mother': '👩',
    'family': '👨‍👩‍👧‍👦',
    'friend': '👥',
    'friends': '👥',
    'brother': '👦',
    'sister': '👧',
    'baby': '👶',
    'kid': '👦',
    'kids': '👦',
    'wife': '👩',
    'husband': '👨',
    'partner': '❤️',

    // Tech
    'laptop': '💻',
    'computer': '💻',
    'code': '💻',
    'coding': '💻',
    'program': '💻',
    'software': '💻',
    'app': '📱',
    'website': '🌐',
    'wifi': '📶',
    'internet': '🌐',
    'printer': '🖨️',
    'charger': '🔌',
    'battery': '🔋',
    'cable': '🔌',
    'headphones': '🎧',
    'earphones': '🎧',
    'camera': '📷',
    'photo': '📷',
    'photos': '📷',
    'backup': '💾',

    // Spiritual & Religious
    'pray': '🙏',
    'prayer': '🙏',
    'temple': '🛕',
    'church': '⛪',
    'mosque': '🕌',
    'god': '🙏',
    'mantra': '🕉️',

    // Documents & Admin
    'visa': '🛂',
    'passport': '🛂',
    'aadhar': '🪪',
    'aadhaar': '🪪',
    'pan': '🪪',
    'license': '🪪',
    'certificate': '📜',
    'document': '📄',
    'documents': '📄',
    'form': '📄',
    'vote': '🗳️',
    'id': '🪪',

    // Weather & Nature
    'rain': '🌧️',
    'umbrella': '☂️',
    'sun': '☀️',
    'cold': '🥶',
    'hot': '🥵',

    // Pets
    'dog': '🐕',
    'cat': '🐱',
    'pet': '🐾',
    'vet': '🏥',
    'puppy': '🐶',
    'kitten': '🐱',

    // Misc
    'key': '🔑',
    'keys': '🔑',
    'lock': '🔒',
    'bag': '👜',
    'backpack': '🎒',
    'shoes': '👟',
    'clothes': '👕',
    'dress': '👗',
    'watch': '⌚',
    'glasses': '👓',
    'sunglasses': '🕶️',
    'wallet': '👛',
    'bottle': '🍼',
    'candle': '🕯️',
    'paint': '🎨',
    'craft': '🎨',
    'sew': '🧵',
    'knit': '🧶',
    'recycle': '♻️',
    'donate': '🤲',
    'volunteer': '🤝',
    'move': '📦',
    'pack': '📦',
    'unpack': '📦',
    'repair': '🔧',
    'fix': '🔧',
    'tool': '🔧',
    'tools': '🧰',
    'bulb': '💡',
    'light': '💡',
    'lamp': '💡',
    'fan': '🌀',
    'ac': '❄️',
    'heater': '🔥',
    'fire': '🔥',
    'alarm': '⏰',
    'timer': '⏱️',
    'clock': '🕐',
    'calendar': '📅',
    'schedule': '📅',
    'plan': '📋',
    'list': '📝',
    'note': '📝',
    'notes': '📝',
    'idea': '💡',
    'think': '🤔',
    'goal': '🎯',
    'goals': '🎯',
    'target': '🎯',
    'win': '🏆',
    'trophy': '🏆',
    'star': '⭐',
    'heart': '❤️',
    'love': '❤️',
    'smile': '😊',
    'laugh': '😂',
    'cry': '😢',
    'sorry': '🙇',
    'help': '🆘',
    'emergency': '🚨',
    'password': '🔐',
    'safe': '🔐',
    'map': '🗺️',
    'direction': '🧭',
    'compass': '🧭',
  };
}
